version: "3.9"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    environment:
      - RI_APP_PORT=5540