version: "3.9"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./infra/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    environment:
      - RI_APP_PORT=5540
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mumuca-bass-dev
      POSTGRES_PASSWORD: mumuca-bass-password
      POSTGRES_DB: mumuca-bass
    volumes:
      - ./infra/postgres.conf:/etc/postgresql/postgresql.conf