spring:
  application:
    name: mumuca-bass
  threads:
    virtual:
      enabled: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/mumuca-bass
    username: mumuca-bass-dev
    password: mumuca-bass-password
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: on
  rabbitmq:
    host: localhost
    port: 5672
    username: mumuca-bass-dev
    password: mumuca-bass-password
    virtual-host: /

mq:
  queues:
    track-download: track-download-queue
    track-download-dlq: track-download-dead-letter-queue
    track-download-status: track-download-status-queue
    track-download-status-dlq: track-download-status-dead-letter-queue
  routing-keys:
    track-download: track.download
    track-download-dlq: track.download.dlq
    track-download-status: track.download.status
    track-download-status-dlq: track.download.status.dlq
  exchanges:
    track: track-exchange
    track-dlx: track-dead-letter-exchange