spring:
  application:
    name: mumuca-bass
  threads:
    virtual:
      enabled: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/mumuca-bass
    username: mumuca-bass-dev
    password: mumuca-bass-password
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: on
